name: darturbation
description: An advanced, context-aware, and behavioral mock data generator for Dart & Flutter.
version: 2.0.1
homepage: https://github.com/mathtechstudio/darturbation
repository: https://github.com/mathtechstudio/darturbation
issue_tracker: https://github.com/mathtechstudio/darturbation/issues

publisher: mathtechstudio

maintainer: Iqbal F <iqbalfauzien@proton.me>

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  uuid: ^4.5.1
  faker: ^2.1.0
  crypto: ^3.0.3
  collection: ^1.18.0

dev_dependencies:
  lints: any
  test: ^1.24.0
  dart_code_metrics_presets: ^2.24.0
  coverage: ^1.8.0